--!MATERIALIZED VIEW

DROP TABLE XXTEST;

DROP MATERIALIZED VIEW XXMV_XXTEST;

CREATE TABLE XXTEST ( A NUMBER PRIMARY KEY, B VARCHAR2(100));

INSERT INTO XXTEST VALUES (1, 'a');

INSERT INTO XXTEST VALUES (2, 'a');

INSERT INTO XXTEST VALUES (3, 'a');

COMMIT;

CREATE SNAPSHOT LOG ON XXTEST;

CREATE MATERIALIZED VIEW XXMV_XXTEST REFRESH FAST AS SELECT * FROM XXTEST;

BEGIN DBMS_UTILITY.EXEC_DDL_STATEMENT('TRUNCATE TABLE XXMV_XXTEST'); END;;

INSERT INTO XXTEST VALUES (4, 'a');

COMMIT;

dbms_mview.REFRESH(mat_view_name,'c',NULL , FALSE, FALSE);
albo
BEGIN DBMS_SNAPSHOT.REFRESH('XXMV_XXTEST'); END;

ORA-32320 REFRESH FAST OF "string"."string" UNSUPPORTED AFTER CONTAINER TABLE
PMOPS
CAUSE: A PARTITION MAINTENANCE OPERATION (PMOP) HAS BEEN PERFORMED ON THE
MATERIALIZED VIEW, AND NO MATERIALIZED VIEW SUPPORTS FAST REFERSH AFTER
CONTAINER TABLE PMOPS.
ACTION: USE REFRESH COMPLETE. NOTE: YOU CAN DETERMINE WHY YOUR
MATERIALIZED VIEW DOES NOT SUPPORT FAST REFRESH AFTER PMOPS USING THE DBMS_
MVIEW.EXPLAIN_MVIEW() API.

SELECT * FROM XXMV_XXTEST;

-- WYKLADA SIE Z BLEDEM - TO LOGICZNE. ALE JAK W TAKIM RAZIE WYKONAC WIDOK POKAZUJACY TYLKO PRZYROSTOWE DANE ?

SELECT * FROM ALL_OBJECTS WHERE OBJECT_NAME LIKE 'XXMV_XXTEST';

-- szersza skladnia:

CREATE MATERIALIZED VIEW APPS.XXP_D_ORG_PH_MV 
TABLESPACE APPS_TS_SUMMARY
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE
START WITH TO_DATE('28-sie-2008 20:00:00','dd-mon-yyyy hh24:mi:ss')
NEXT (trunc(sysdate+1) + interval '20' hour)  
[WITH PRIMARY KEY | WITH ROWID]
AS 
select ...

-- jeszcze szersza sk³adnia -> toad, menu create


