PROMPT UWAGA, SKRYPT USUNIE UZYTKOWNIKOW MAIN,USER_1,USER_2 I SYNONIM PUBLICZNY POL(JESLI ISTNIEJA)
PROMPT PODAJ HAS£O DLA U¯YTKOWNIKA SYSTEM
CONNECT SYSTEM;
DROP USER MAIN CASCADE;
DROP USER USER_1 CASCADE;
DROP USER USER_2 CASCADE;

CREATE USER MAIN IDENTIFIED BY MAIN;
GRANT DBA TO MAIN;

PROMPT LOGOWANIE DO U¯YTKOWNIKA MAIN 
PROMPT WprowadŸ serwis lub naciœnij klawisz ENTER 
CONNECT MAIN/MAIN@&&SERWIS

CREATE TABLE POLISY
  (NR VARCHAR2(10)
  ,USER_NAME VARCHAR2(30) DEFAULT USER)
/  
CREATE VIEW POL AS SELECT * FROM POLISY WHERE USER_NAME = USER;

CREATE USER USER_1 IDENTIFIED BY USER_1;
GRANT "CONNECT" TO USER_1;
GRANT ALL ON MAIN.POL TO USER_1;

CREATE USER USER_2 IDENTIFIED BY USER_2;
GRANT "CONNECT" TO USER_2;
GRANT ALL ON MAIN.POL TO USER_2;

DROP PUBLIC SYNONYM POL;
CREATE PUBLIC SYNONYM POL FOR POL;

CONNECT USER_1/USER_1@&&SERWIS;
INSERT INTO POL (NR) VALUES ('1 USER_1');
INSERT INTO POL (NR) VALUES ('2 USER_1');
COMMIT;

PROMPT SELECT WYŒWIETLI 2 REKORDY
SELECT * FROM POL;  

CONNECT USER_2/USER_2@&&SERWIS;
INSERT INTO POL (NR) VALUES ('1 USER_2');
INSERT INTO POL (NR) VALUES ('2 USER_2');
COMMIT;

PROMPT SELECT WYŒWIETLI 2 REKORDY. REKORDY U¯YTKOWNIKA USER_1 S¥ NIEWIDOCZNE
SELECT * FROM POL;  

CONNECT MAIN/MAIN&&SERWIS
PROMPT SELECT WYŒWIETLI WSZYSTKIE 4 REKORDY
SELECT * FROM POLISY;  

CONNECT USER_1/USER_1@&&SERWIS
PROMPT POLECENIE USUNIE TYLKO REKORDY U¯YTKOWNIKA USER_1
DELETE FROM POL;

CONNECT MAIN/MAIN&&SERWIS
PROMPT SELECT WYŒWIETLI 2 REKORDY
SELECT * FROM POLISY;  

